### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/apple-touch-icon-152x152-precomposed.png") のようなエラーが出る

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#197]
ログにこんなエラーが出てます。

```
Jan 16 00:55:16 rubyist-connect app/web.1:  [11e6975d-b425-4da6-a052-0c4c21d45554] Started GET "/apple-touch-icon-152x152-precomposed.png" for 108.162.226.49 at 2015-01-15 15:55:16 +0000 
Jan 16 00:55:16 rubyist-connect app/web.1:  [11e6975d-b425-4da6-a052-0c4c21d45554]  
Jan 16 00:55:16 rubyist-connect heroku/router:  at=info method=GET path="/apple-touch-icon-152x152-precomposed.png" host=rubyist.co request_id=11e6975d-b425-4da6-a052-0c4c21d45554 fwd="112.68.144.27,108.162.226.49" dyno=web.1 connect=1ms service=37ms status=404 bytes=1804 
Jan 16 00:55:16 rubyist-connect app/web.1:  ActionController::RoutingError (No route matches [GET] "/apple-touch-icon-152x152-precomposed.png"): 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>' 
Jan 16 00:55:16 rubyist-connect app/web.1:  [8d1a0847-1668-4768-8ead-d695f5f5c587] Started GET "/apple-touch-icon-152x152.png" for 103.22.200.84 at 2015-01-15 15:55:16 +0000 
Jan 16 00:55:16 rubyist-connect app/web.1:  [8d1a0847-1668-4768-8ead-d695f5f5c587]  
Jan 16 00:55:16 rubyist-connect app/web.1:  ActionController::RoutingError (No route matches [GET] "/apple-touch-icon-152x152.png"): 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect heroku/router:  at=info method=GET path="/apple-touch-icon-152x152.png" host=rubyist.co request_id=8d1a0847-1668-4768-8ead-d695f5f5c587 fwd="112.68.144.27,103.22.200.84" dyno=web.1 connect=1ms service=38ms status=404 bytes=1804 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load' 
Jan 16 00:55:16 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>' 
Jan 16 00:55:17 rubyist-connect app/web.1:  [acdb46e6-e1f0-4589-8d96-1fcac7189a3b] Started GET "/apple-touch-icon.png" for 108.162.226.62 at 2015-01-15 15:55:17 +0000 
Jan 16 00:55:17 rubyist-connect app/web.1:  [acdb46e6-e1f0-4589-8d96-1fcac7189a3b]  
Jan 16 00:55:17 rubyist-connect app/web.1:  ActionController::RoutingError (No route matches [GET] "/apple-touch-icon.png"): 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.9.8.273/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load' 
Jan 16 00:55:17 rubyist-connect app/web.1:    vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>' 
Jan 16 00:55:17 rubyist-connect heroku/router:  at=info method=GET path="/apple-touch-icon.png" host=rubyist.co request_id=acdb46e6-e1f0-4589-8d96-1fcac7189a3b fwd="112.68.144.27,108.162.226.62" dyno=web.1 connect=11ms service=15ms status=404 bytes=1804 
```

**Comment by springaki** [comment]
参考まで http://qiita.com/matsui_q/items/c3d32181a0661a908291

**Comment by kanizmb** [comment]
256×256px 画像作りました。ご活用ください〜。
（画像やデザインに関係するタスク、私以外の方がやってくださってかまいませんよー？）
![apple-touch-icon](https://cloud.githubusercontent.com/assets/4459676/5773769/903a6dfe-9da9-11e4-988e-0f2aeebea642.png)

**Comment by JunichiIto** [comment]
ありがとうございます！

> 画像やデザインに関係するタスク、私以外の方がやってくださってかまいませんよー？

はい、ごもっともです・・・・ :sweat: 

いつまでも @kanizmb さんに依存してたらダメですよね～。

Adobe製品を使うような作業はちょっと無理ですが、それ以外の作業はプログラマもトライしてダメ出し受けないといけませんね。

この記事で紹介されてるみたいに。

http://www.sonicgarden.jp/201501_interview_designer1

**Comment by yuji-shimoda** [comment]
ドキュメント整備とか、Facebookページなどのタスクが完了したら、デザイン系のissue に着手しますので、その時はレビュー宜しくお願いしますー @kanizmb

**Comment by springaki** [comment]
アクセスして Errorが発生しなくなったのを確認。

**Comment by springaki** [comment]
参考URL: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4

**Comment by yuji-shimoda** [comment]
対応ありがとうございますー :+1:

**Comment by springaki** [comment]
Before:
![img_0747](https://cloud.githubusercontent.com/assets/534628/5778490/05a5ecf0-9ddf-11e4-9853-a6326f78c1b0.png)

After:
![img_0748](https://cloud.githubusercontent.com/assets/534628/5778509/1f5b386c-9ddf-11e4-8b52-0d7b6106d0a5.png)

**Comment by kanizmb** [comment]
最終的な目標は、チームの一人一人が自分で作るアプリ際の技術を身につけることだと思っているので、デザインの作業を独り占めしないように気をつけています。
この考えから、トップページは誰でも編集できるようほぼ画像を使っていません。
面倒臭いとかではないので、その辺り誤解なきようにお願いしますね！
デザイナーでないと厳しい部分は引き続き担当しますし、レビューも :ok_woman:  です〜。
あと自分がやりたい所は遠慮なく奪っていきます（笑

@springaki 
アイコン設定ありがとうございます！:sparkles:

**Comment by springaki** [comment]
@kanizmb よい方向性だと思っています。@kanizmb もコードがんがん書いてねー :smile_cat:

**Comment by JunichiIto** [comment]
@kanizmb さすが、カニパイセン！
